
FROM python:3.14


WORKDIR /code


COPY ./requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


COPY ./src /code/src
COPY ./api /code/api

CMD ["fastapi", "run", "api/app.py", "--port", "80"]